name: Build & Deploy Angular App

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install Angular CLI and dependencies
        run: |
          npm install -g @angular/cli
          npm ci

      - name: Build Angular app
        run: ng build --configuration=production --base-href /dist/portfolio/browser/ 
        env:
          NODE_OPTIONS: --max-old-space-size=8192 # Increase memory limit for Angular CLI if needed

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./dist/portfolio # Replace <your-project-name> with the name of your Angular project

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/portfolio # Replace <your-project-name> with the name of your Angular project
          publish_branch: gh-pages # The branch the action should deploy to.
